services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: beloz-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=beloz_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d beloz_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - beloz-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: beloz-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_NAME=beloz_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - beloz-network

networks:
  beloz-network:
    driver: bridge

volumes:
  postgres_data:
